### ISSUE TITLE
Daemons that insist on not being run as root should all provide -username flag

### ISSUE THREAD

**Issue by masiulaniec** [Symantec/Dominator#444]
```
# filegen-server 
Do not run the filegen server as root
# imageserver
Do not run the Image Server as root
# dominator -alsoLogToStderr
-username argument missing
#
```
This should be homogenized: `filegen-server` and `imageserver` should follow `dominator` and accept a `-username` flag. Right now, the easiest way to treat these binaries equally is by setuid'ing them all to a non-privileged user, but setuid is a security anti-pattern...

(Btw, `mdbd` seems like a good candidate for the set of daemons that don't require root.)

**Comment by rgooch** [comment]
Agreed. Send a PR, or poke me in a couple of weeks (I've got a stack of changes I'm in the middle of:-).

**Comment by rgooch** [comment]
Actually, on further consideration, it's a bit ugly what `dominator` is doing (OS thread pinning, changing UID and re-execing itself). Maybe this should be left to be a responsibility of the init script (which I note they all do), so instead of adding that code to `filegen-server` and `imageserver`, maybe it's better to remove it from `dominator`.

**Comment by masiulaniec** [comment]
I like this approach too.
